/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author MOR
 */
public class Home extends javax.swing.JFrame {

    public String email;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    public Home(String userEmail) {
        initComponents();
        email = userEmail;
        if (!email.equals("admin@ymail.com")) {
            btnCategory.setVisible(false);
            btnNewProduct.setVisible(false);
            btnViewEditDeleteProduct.setVisible(false);
            btnVerifyUser.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();
            btnCategory = new javax.swing.JButton();
            btnNewProduct = new javax.swing.JButton();
            btnViewEditDeleteProduct = new javax.swing.JButton();
            btnVerifyUser = new javax.swing.JButton();
            jLabel1 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jButton1.setBackground(new java.awt.Color(153, 255, 204));
            jButton1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
            jButton1.setText("Logout");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

            jButton2.setBackground(new java.awt.Color(153, 255, 204));
            jButton2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
            jButton2.setText("Place Order");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

            jButton3.setBackground(new java.awt.Color(153, 255, 204));
            jButton3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
            jButton3.setText("View Bill and Order Placed Details");
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

            jButton4.setBackground(new java.awt.Color(153, 255, 204));
            jButton4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
            jButton4.setText("Change Password");
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, -1));

            jButton5.setBackground(new java.awt.Color(153, 255, 204));
            jButton5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
            jButton5.setText("Change Security Question");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, -1, -1));

            jButton6.setBackground(new java.awt.Color(153, 255, 204));
            jButton6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
            jButton6.setText("Exit");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton6ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 30, -1, -1));

            btnCategory.setBackground(new java.awt.Color(255, 204, 51));
            btnCategory.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            btnCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
            btnCategory.setText("Manage Category");
            btnCategory.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnCategoryActionPerformed(evt);
                  }
            });
            getContentPane().add(btnCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 760, -1, -1));

            btnNewProduct.setBackground(new java.awt.Color(255, 204, 51));
            btnNewProduct.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            btnNewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add new.png"))); // NOI18N
            btnNewProduct.setText("New Product");
            btnNewProduct.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnNewProductActionPerformed(evt);
                  }
            });
            getContentPane().add(btnNewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 760, -1, -1));

            btnViewEditDeleteProduct.setBackground(new java.awt.Color(255, 204, 51));
            btnViewEditDeleteProduct.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            btnViewEditDeleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
            btnViewEditDeleteProduct.setText("View, Edit and Delete Product");
            btnViewEditDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnViewEditDeleteProductActionPerformed(evt);
                  }
            });
            getContentPane().add(btnViewEditDeleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 760, -1, -1));

            btnVerifyUser.setBackground(new java.awt.Color(255, 204, 51));
            btnVerifyUser.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            btnVerifyUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
            btnVerifyUser.setText("Verify Users");
            btnVerifyUser.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnVerifyUserActionPerformed(evt);
                  }
            });
            getContentPane().add(btnVerifyUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 760, -1, -1));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home-background-image.png"))); // NOI18N
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Want to Logout?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do You Want to Close the Application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new ChangePassword(email).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

      private void btnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryActionPerformed
            // TODO add your handling code here:
            new ManageCategory().setVisible(true);
      }//GEN-LAST:event_btnCategoryActionPerformed

      private void btnNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProductActionPerformed
            // TODO add your handling code here:
            new AddNewProduct().setVisible(true);
      }//GEN-LAST:event_btnNewProductActionPerformed

      private void btnViewEditDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEditDeleteProductActionPerformed
            // TODO add your handling code here:
            new ViewEditDeleteProduct().setVisible(true);
      }//GEN-LAST:event_btnViewEditDeleteProductActionPerformed

      private void btnVerifyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyUserActionPerformed
            // TODO add your handling code here:
            new VerifyUsers().setVisible(true);
      }//GEN-LAST:event_btnVerifyUserActionPerformed

      private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
            setVisible(false);
            new PlaceOrder(email).setVisible(true);
      }//GEN-LAST:event_jButton2ActionPerformed

      private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // TODO add your handling code here:
            new ViewBillOrderPlacedDetails().setVisible(true);
      }//GEN-LAST:event_jButton3ActionPerformed

      private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            // TODO add your handling code here:
            new ChangeSecurityQuestion(email).setVisible(true);
      }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnCategory;
      private javax.swing.JButton btnNewProduct;
      private javax.swing.JButton btnVerifyUser;
      private javax.swing.JButton btnViewEditDeleteProduct;
      private javax.swing.JButton jButton1;
      private javax.swing.JButton jButton2;
      private javax.swing.JButton jButton3;
      private javax.swing.JButton jButton4;
      private javax.swing.JButton jButton5;
      private javax.swing.JButton jButton6;
      private javax.swing.JLabel jLabel1;
      // End of variables declaration//GEN-END:variables
}
