/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import common.OpenPdf;
import dao.CategoryDao;
import dao.ProductDao;
import dao.billDao;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Bill;
import model.Category;
import model.Product;

/**
 *
 * @author MOR
 */
public class PlaceOrder extends javax.swing.JFrame {

      public String userEmail;
      public int billId = 1; // billId created to be used later when generating bill pdf
      public int grandTotal = 0;
      public int productPrice = 0;
      public int productTotal = 0;
      public String emailPattern = "^[a-zA-Z0-9._]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
      public String mobileNumberPatter = "^[0-9]*$";

      /**
       * Creates new form PlaceOrder
       */
      public PlaceOrder() {
            initComponents();
      }

      public PlaceOrder(String email) {
            initComponents();
            txtProName.setEditable(false);
            txtProPrice.setEditable(false);
            txtProTotal.setEditable(false);
            btnAddtoCart.setEnabled(false);
            btnGenerateBillPrint.setEnabled(false);
            JFormattedTextField tf = ((JSpinner.DefaultEditor) jSpinner1.getEditor()).getTextField();
            tf.setEditable(false);
            userEmail = email;
      }

      public void productNameByCategory(String category) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ArrayList<Product> list = ProductDao.getAllRecordsByCategory(category);
            Iterator<Product> itr = list.iterator();
            while (itr.hasNext()) {
                  Product productObj = itr.next();
                  dtm.addRow(new Object[]{productObj.getName()});
            }
      }

      public void filterProductByName(String name, String category) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ArrayList<Product> list = ProductDao.filterProductByName(name, category);
            Iterator<Product> itr = list.iterator();
            while (itr.hasNext()) {
                  Product productObj = itr.next();
                  dtm.addRow(new Object[]{productObj.getName()});
            }
      }

      public void clearProductFields() {
            txtProName.setText("");
            txtProPrice.setText("");
            txtProTotal.setText("");
            jSpinner1.setValue(1);
            btnAddtoCart.setEnabled(false);
      }

      public void validateFields() {
            String customerName = txtCusName.getText();
            String customerMobile = txtCusMobile.getText();
            String customerEmail = txtCusEmail.getText();
            if (!customerName.equals("") && !customerEmail.equals("") && customerMobile.matches(mobileNumberPatter) && customerMobile.length() == 10 &&
                    customerEmail.matches(emailPattern) && grandTotal > 0) {
                  btnGenerateBillPrint.setEnabled(true);
            } else {
                  btnGenerateBillPrint.setEnabled(false);
            }
      }

      /**
       * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
       * regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jLabel1 = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            jLabel2 = new javax.swing.JLabel();
            lblbill = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jLabel5 = new javax.swing.JLabel();
            txtCusName = new javax.swing.JTextField();
            jLabel6 = new javax.swing.JLabel();
            txtCusMobile = new javax.swing.JTextField();
            jLabel7 = new javax.swing.JLabel();
            txtCusEmail = new javax.swing.JTextField();
            jLabel8 = new javax.swing.JLabel();
            jComboBox1 = new javax.swing.JComboBox<>();
            jLabel9 = new javax.swing.JLabel();
            txtSearch = new javax.swing.JTextField();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            jLabel10 = new javax.swing.JLabel();
            txtProName = new javax.swing.JTextField();
            jLabel11 = new javax.swing.JLabel();
            jSpinner1 = new javax.swing.JSpinner();
            jLabel12 = new javax.swing.JLabel();
            txtProPrice = new javax.swing.JTextField();
            jLabel13 = new javax.swing.JLabel();
            txtProTotal = new javax.swing.JTextField();
            btnClear = new javax.swing.JButton();
            btnAddtoCart = new javax.swing.JButton();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTable2 = new javax.swing.JTable();
            jLabel14 = new javax.swing.JLabel();
            lblGrandTotal = new javax.swing.JLabel();
            btnGenerateBillPrint = new javax.swing.JButton();
            jLabel16 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setUndecorated(true);
            addComponentListener(new java.awt.event.ComponentAdapter() {
                  public void componentShown(java.awt.event.ComponentEvent evt) {
                        formComponentShown(evt);
                  }
            });
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
            jLabel1.setText("Place Order");
            getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, -1, -1));

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel2.setForeground(new java.awt.Color(255, 255, 255));
            jLabel2.setText("Bill Id:");
            getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 78, 50, -1));

            lblbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            lblbill.setForeground(new java.awt.Color(255, 255, 255));
            lblbill.setText("--");
            getContentPane().add(lblbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 37, -1));

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel4.setForeground(new java.awt.Color(255, 255, 255));
            jLabel4.setText("Customer Details:");
            getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 116, -1, -1));

            jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel5.setForeground(new java.awt.Color(255, 255, 255));
            jLabel5.setText("Name");
            getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 154, 61, -1));

            txtCusName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            txtCusName.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtCusNameKeyReleased(evt);
                  }
            });
            getContentPane().add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 189, 251, -1));

            jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(255, 255, 255));
            jLabel6.setText("Mobile Number");
            getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 230, -1, -1));

            txtCusMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            txtCusMobile.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtCusMobileKeyReleased(evt);
                  }
            });
            getContentPane().add(txtCusMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 265, 251, -1));

            jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel7.setForeground(new java.awt.Color(255, 255, 255));
            jLabel7.setText("Email");
            getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 306, 57, -1));

            txtCusEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            txtCusEmail.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtCusEmailKeyReleased(evt);
                  }
            });
            getContentPane().add(txtCusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 341, 251, -1));

            jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel8.setForeground(new java.awt.Color(255, 255, 255));
            jLabel8.setText("Category");
            getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 78, 84, -1));

            jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jComboBox1ActionPerformed(evt);
                  }
            });
            getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 113, 251, -1));

            jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel9.setForeground(new java.awt.Color(255, 255, 255));
            jLabel9.setText("Search");
            getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 154, 84, -1));

            txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyReleased(java.awt.event.KeyEvent evt) {
                        txtSearchKeyReleased(evt);
                  }
            });
            getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 189, 251, -1));

            jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Name"
                  }
            ));
            jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable1MouseClicked(evt);
                  }
            });
            jScrollPane1.setViewportView(jTable1);

            getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 230, 251, -1));

            jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel10.setForeground(new java.awt.Color(255, 255, 255));
            jLabel10.setText("Name");
            getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 78, 43, -1));

            txtProName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            getContentPane().add(txtProName, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 114, 251, -1));

            jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel11.setForeground(new java.awt.Color(255, 255, 255));
            jLabel11.setText("Quantity");
            getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 154, -1, -1));

            jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
                  public void stateChanged(javax.swing.event.ChangeEvent evt) {
                        jSpinner1StateChanged(evt);
                  }
            });
            getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 189, 251, -1));

            jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel12.setForeground(new java.awt.Color(255, 255, 255));
            jLabel12.setText("Price");
            getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 78, 43, -1));

            txtProPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            getContentPane().add(txtProPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 114, 251, -1));

            jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel13.setForeground(new java.awt.Color(255, 255, 255));
            jLabel13.setText("Total");
            getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 154, 43, -1));

            txtProTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            getContentPane().add(txtProTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1135, 189, 251, -1));

            btnClear.setBackground(new java.awt.Color(0, 0, 0));
            btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            btnClear.setForeground(new java.awt.Color(255, 255, 255));
            btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
            btnClear.setText("Clear");
            btnClear.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnClearActionPerformed(evt);
                  }
            });
            getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 230, -1, -1));

            btnAddtoCart.setBackground(new java.awt.Color(0, 0, 0));
            btnAddtoCart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            btnAddtoCart.setForeground(new java.awt.Color(255, 255, 255));
            btnAddtoCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add to cart(1).png"))); // NOI18N
            btnAddtoCart.setText("Add to Cart");
            btnAddtoCart.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAddtoCartActionPerformed(evt);
                  }
            });
            getContentPane().add(btnAddtoCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1252, 230, -1, -1));

            jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Name", "Price", "Quantity", "Total"
                  }
            ));
            jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mouseClicked(java.awt.event.MouseEvent evt) {
                        jTable2MouseClicked(evt);
                  }
            });
            jScrollPane2.setViewportView(jTable2);

            getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 540, 370));

            jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel14.setForeground(new java.awt.Color(255, 255, 255));
            jLabel14.setText("Grand Total(Rs):");
            getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, -1, -1));

            lblGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            lblGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
            lblGrandTotal.setText("000");
            getContentPane().add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 670, 43, -1));

            btnGenerateBillPrint.setBackground(new java.awt.Color(0, 0, 0));
            btnGenerateBillPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            btnGenerateBillPrint.setForeground(new java.awt.Color(255, 255, 255));
            btnGenerateBillPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generate bill & print.png"))); // NOI18N
            btnGenerateBillPrint.setText("Generate Bill & Print");
            btnGenerateBillPrint.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnGenerateBillPrintActionPerformed(evt);
                  }
            });
            getContentPane().add(btnGenerateBillPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 670, -1, -1));

            jLabel16.setBackground(new java.awt.Color(0, 153, 153));
            jLabel16.setOpaque(true);
            getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1930, 1090));

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
            setVisible(false);
            new Home(userEmail).setVisible(true);
      }//GEN-LAST:event_jButton1ActionPerformed

      private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
            // TODO add your handling code here:
            billId = Integer.parseInt(billDao.getId());
            lblbill.setText(billDao.getId());
            ArrayList<Category> list = CategoryDao.getAllRecords();
            Iterator<Category> itr = list.iterator();
            while (itr.hasNext()) {
                  Category categoryObj = itr.next();
                  jComboBox1.addItem(categoryObj.getName());
            }
            String category = (String) jComboBox1.getSelectedItem();
            productNameByCategory(category);
      }//GEN-LAST:event_formComponentShown

      private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
            // TODO add your handling code here:
            String name = txtSearch.getText();
            String category = (String) jComboBox1.getSelectedItem();
            filterProductByName(name, category);
      }//GEN-LAST:event_txtSearchKeyReleased

      private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            // TODO add your handling code here:
            int index = jTable1.getSelectedRow();
            TableModel model = jTable1.getModel();
            String productName = model.getValueAt(index, 0).toString();
            Product product = ProductDao.getProductByName(productName);
            txtProName.setText(product.getName());
            txtProPrice.setText(product.getPrice());
            jSpinner1.setValue(1);
            txtProTotal.setText(product.getPrice());
            productPrice = Integer.parseInt(product.getPrice());
            productTotal = Integer.parseInt(product.getPrice());
            btnAddtoCart.setEnabled(true);
      }//GEN-LAST:event_jTable1MouseClicked

      private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
            // TODO add your handling code here:
            int quantity = (Integer) jSpinner1.getValue();
            if (quantity <= 1) {
                  jSpinner1.setValue(1);
                  quantity = 1;
            }
            productTotal = productPrice * quantity;
            txtProTotal.setText(String.valueOf(productTotal));
      }//GEN-LAST:event_jSpinner1StateChanged

      private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
            // TODO add your handling code here:
            String category = (String) jComboBox1.getSelectedItem();
            productNameByCategory(category);
      }//GEN-LAST:event_jComboBox1ActionPerformed

      private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
            // TODO add your handling code here:
            clearProductFields();
      }//GEN-LAST:event_btnClearActionPerformed

      private void btnAddtoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoCartActionPerformed
            // TODO add your handling code here:
            String name = txtProName.getText();
            String price = txtProPrice.getText();
            String quantity = String.valueOf(jSpinner1.getValue());
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.addRow(new Object[]{name, price, quantity, productTotal});
            grandTotal = grandTotal + productTotal;
            lblGrandTotal.setText(String.valueOf(grandTotal));

            clearProductFields();
            validateFields();
      }//GEN-LAST:event_btnAddtoCartActionPerformed

      private void txtCusNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusNameKeyReleased
            // TODO add your handling code here:
            validateFields();
      }//GEN-LAST:event_txtCusNameKeyReleased

      private void txtCusMobileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusMobileKeyReleased
            // TODO add your handling code here:
            validateFields();
      }//GEN-LAST:event_txtCusMobileKeyReleased

      private void txtCusEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCusEmailKeyReleased
            // TODO add your handling code here:
            validateFields();
      }//GEN-LAST:event_txtCusEmailKeyReleased

      private void btnGenerateBillPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillPrintActionPerformed
            // TODO add your handling code here:
            String customerName = txtCusName.getText();
            String customerMobileNumber = txtCusMobile.getText();
            String customerEmail = txtCusEmail.getText();
            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            Date date = new Date();
            String todayDate = dFormat.format(date);
            String total = String.valueOf(grandTotal);
            String createdBy = userEmail;
            Bill bill = new Bill();
            bill.setId(billId);
            bill.setName(customerName);
            bill.setMobileNumber(customerMobileNumber);
            bill.setEmail(customerEmail);
            bill.setDate(todayDate);
            bill.setTotal(total);
            bill.setCreatedBy(createdBy);
            billDao.save(bill);

            // creating documents
            String path = "E:\\";
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                  PdfWriter.getInstance(doc, new FileOutputStream(path + "" + billId + ".pdf"));
                  doc.open();
                  Paragraph cafeName = new Paragraph("\t\t\t\t\t\t\t\t\t\t\t\tRestaurant Management System\n");
                  doc.add(cafeName);
                  Paragraph starLine = new Paragraph(
                   "\n*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^*^\n\n");
                  doc.add(starLine);
                  Paragraph paragraph3 = new Paragraph("\t Bill ID: "+billId+"\n\n Customer Name: "+customerName+"\n\n Total Paid: "+grandTotal+"\n");
                  doc.add(paragraph3);
                  doc.add(starLine);
                  PdfPTable tb1 = new PdfPTable(4);
                  tb1.addCell("Name");
                  tb1.addCell("Price");
                  tb1.addCell("Quantity");
                  tb1.addCell("Total");
                  for(int i = 0; i < jTable2.getRowCount(); i++){
                        String n = jTable2.getValueAt(i, 0).toString();
                        String p = jTable2.getValueAt(i, 1).toString();
                        String q = jTable2.getValueAt(i, 2).toString();
                        String t = jTable2.getValueAt(i, 3).toString();
                        tb1.addCell(n);
                        tb1.addCell(p);
                        tb1.addCell(q);
                        tb1.addCell(t);
                  }
                  doc.add(tb1);
                  doc.add(starLine);
                  Paragraph thanksMessage = new Paragraph("\n\nThank You - Please Visit Again...");
                  doc.add(thanksMessage);
                  // open pdf
                  OpenPdf.openById(String.valueOf(billId));
            } 
            catch (Exception e) {
                  JOptionPane.showMessageDialog(null, e);
            }
            doc.close();
            setVisible(false);
            new PlaceOrder(createdBy).setVisible(true);
      }//GEN-LAST:event_btnGenerateBillPrintActionPerformed

      private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
            // TODO add your handling code here:
            int index = jTable2.getSelectedRow();
            int a = JOptionPane.showConfirmDialog(null, "Do You Want to Remove this Product", "Select", JOptionPane.YES_NO_OPTION);
            if(a==0){
                  TableModel model = jTable2.getModel();
                  String total = model.getValueAt(index, 3).toString();
                  grandTotal = grandTotal - Integer.parseInt(total);
                  lblGrandTotal.setText(String.valueOf(grandTotal));
                  ((DefaultTableModel) jTable2.getModel()).removeRow(index);
            }
      }//GEN-LAST:event_jTable2MouseClicked

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(PlaceOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new PlaceOrder().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnAddtoCart;
      private javax.swing.JButton btnClear;
      private javax.swing.JButton btnGenerateBillPrint;
      private javax.swing.JButton jButton1;
      private javax.swing.JComboBox<String> jComboBox1;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel10;
      private javax.swing.JLabel jLabel11;
      private javax.swing.JLabel jLabel12;
      private javax.swing.JLabel jLabel13;
      private javax.swing.JLabel jLabel14;
      private javax.swing.JLabel jLabel16;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel4;
      private javax.swing.JLabel jLabel5;
      private javax.swing.JLabel jLabel6;
      private javax.swing.JLabel jLabel7;
      private javax.swing.JLabel jLabel8;
      private javax.swing.JLabel jLabel9;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JSpinner jSpinner1;
      private javax.swing.JTable jTable1;
      private javax.swing.JTable jTable2;
      private javax.swing.JLabel lblGrandTotal;
      private javax.swing.JLabel lblbill;
      private javax.swing.JTextField txtCusEmail;
      private javax.swing.JTextField txtCusMobile;
      private javax.swing.JTextField txtCusName;
      private javax.swing.JTextField txtProName;
      private javax.swing.JTextField txtProPrice;
      private javax.swing.JTextField txtProTotal;
      private javax.swing.JTextField txtSearch;
      // End of variables declaration//GEN-END:variables
}
